baseurl = "http://localhost:1313/"
title = "José Cardona"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[markup.goldmark.renderer]
  unsafe = true

[params]
  author = "José Manuel Cardona Arias"
  info = "Building data-driven tools for equitable policy"
  description = "José Cardona's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/portrait.jpg"
  #gravatar = "mcardonaarias96@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2024

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/manucardona"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://linkedin.com/in/jmcarias"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://x.com/ManiArias"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Projects"
  url = "projects/"
  weight = 2
[[menu.main]]
  name = "Publications"
  weight = 3
  url  = "publications/"
[[menu.main]]
  name = "Blog"
  weight = 4
  url  = "posts/"
